import type { Metadata } from "next";
import { Bai_Jamjuree } from "next/font/google";
import "./globals.css";



const baiJamjuree = Bai_Jamjuree({
  subsets: ["latin"],
  weight: ["400", "600"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${baiJamjuree.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
